#!/usr/bin/env bash
# Factors Challenge with Updated Variable Names

check_factors() {
    if [ $# -ne 3 ]; then
        args=("$@")
        count=0
        product=1
        for a in "${args[@]}"; do
            if [ $count -gt 1 ]; then
                product=$(echo "$a * $product" | bc)
            fi
            count=$((count + 1))
        done
    else
        product=$3
    fi

    num1=$2
    num=$(echo "$1" | tr ':' '=')

    result=$(echo "if ($product > $num1) 1 else 0" | bc)
    if ((result == 1)); then
        temp=$num1
        num1=$product
        product=$temp
    fi

    echo "$num$num1*$product"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read line; do
        factor_result=$(factor "$line")
        check_factors $factor_result
    done < "$1"
fi
